CREATE TABLE USER (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255),
  age INTEGER
);

CREATE TABLE PRODUCT (
  id INTEGER PRIMARY KEY,
  title VARCHAR(255),
  price DECIMAL(19,2),
  owner_id INTEGER NOT NULL,
  CONSTRAINT ownerIdFk FOREIGN KEY (owner_id) REFERENCES USER(id)
);

CREATE TABLE AUTHENTICATION_TOKEN(
  id INTEGER PRIMARY KEY,
  value VARCHAR(255) UNIQUE,
  user_id INTEGER,
  CONSTRAINT userFk FOREIGN KEY (user_id) REFERENCES USER(id)
);

INSERT INTO USER VALUES
(1, 'aliaksey', 28),
(2, 'not aliaksey', 21);

INSERT INTO PRODUCT VALUES
(1, 'good gashishshs', 20, 1),
(2, 'break disk', 20, 1);

INSERT INTO AUTHENTICATION_TOKEN VALUES
(1, '123', 1);
